/* --- sprite_name, sprite_atlas_path, sprite_source, sprite_offset --- */
StaticSprite(ground_arctic, "scenic/biome_ground", v4(0.0f, 0.0f, 100.0f, 150.0f), v2(0.0f, 147.0f))
StaticSprite(ground_desert, "scenic/biome_ground", v4(100.0f, 0.0f, 100.0f, 150.0f), v2(0.0f, 147.0f))
StaticSprite(ground_plains, "scenic/biome_ground", v4(200.0f, 0.0f, 100.0f, 150.0f), v2(0.0f, 147.0f))

StaticSprite(player, "entity/player/temp_player", v4(0.0f, 0.0f, 14.0f, 35.0f), v2(0.0f, 0.0f))

StaticSprite(flint_sword_icon, "item/flint_sword", v4(0.0f, 0.0f, 16.0f, 16.0f), v2(6.0f, 2.0f))
StaticSprite(flint_sword_ground, "item/flint_sword_ground", v4(0.0f, 0.0f, 24.0f, 24.0f), v2(0.0f, 0.0f))

StaticSprite(shia, "item/shia", v4(0, 0, 800, 1200), v2(0, 0))

// Background
StaticSprite(far_mountains, "scenic/mountains", v4(0.0f, 0.0f, 600.0f, 160.0f), v2(0.0f, 5.0f))
StaticSprite(mid_mountains, "scenic/mountains", v4(0.0f, 160.0f, 600.0f, 90.0f), v2(0.0f, 10.0f))

StaticSprite(cloud_v1, "scenic/clouds", v4(0.0f, 0.0f, 80.0f, 25.0f), v2(0.0f, 0.0f))
StaticSprite(cloud_v2, "scenic/clouds", v4(80.0f, 0.0f, 80.0f, 25.0f), v2(0.0f, 0.0f))
StaticSprite(cloud_v3, "scenic/clouds", v4(160.0f, 0.0f, 80.0f, 25.0f), v2(0.0f, 0.0f))
StaticSprite(cloud_v4, "scenic/clouds", v4(0.0f, 25.0f, 80.0f, 25.0f), v2(0.0f, 0.0f))
StaticSprite(cloud_v5, "scenic/clouds", v4(80.0f, 25.0f, 80.0f, 25.0f), v2(0.0f, 0.0f))
StaticSprite(cloud_v6, "scenic/clouds", v4(160.0f, 25.0f, 80.0f, 25.0f), v2(0.0f, 0.0f))

// Forest
StaticSprite(ground_forest, "scenic/forest_ground", v4(0.0f, 8.0f, 100.0f, 90.0f), v2(0.0f, 87.0f))
StaticSprite(ground_rocks_v1, "scenic/forest_ground", v4(0.0f, 0.0f, 100.0f, 4.0f), v2(0.0f, 0.0f))
StaticSprite(ground_rocks_v2, "scenic/forest_ground", v4(0.0f, 4.0f, 100.0f, 4.0f), v2(0.0f, 0.0f))

StaticSprite(pine_tree_v1, "scenic/trees/pine_tree", v4(0.0f, 0.0f, 90.0f, 170.0f), v2(0.0f, 0.0f))

StaticSprite(hills_1_v1, "scenic/background/bg1_hills", v4(0.0f, 0.0f, 200.0f, 35.0f), v2(0.0f, 20.0f))
StaticSprite(hills_1_v2, "scenic/background/bg1_hills", v4(0.0f, 35.0f, 200.0f, 35.0f), v2(0.0f, 20.0f))

StaticSprite(bg1_shrub_v1, "scenic/background/vegetation", v4(0.0f, 0.0f, 50.0f, 25.0f), v2(0.0f, 0.0f))
StaticSprite(bg1_shrub_v2, "scenic/background/vegetation", v4(50.0f, 0.0f, 50.0f, 25.0f), v2(0.0f, 0.0f))
StaticSprite(bg1_shrub_v3, "scenic/background/vegetation", v4(100.0f, 0.0f, 50.0f, 25.0f), v2(0.0f, 0.0f))

StaticSprite(bg1_sapling_v1, "scenic/background/vegetation", v4(75.0f, 25.0f, 20.0f, 40.0f), v2(0.0f, 0.0f))
StaticSprite(bg1_sapling_v2, "scenic/background/vegetation", v4(95.0f, 25.0f, 20.0f, 40.0f), v2(0.0f, 0.0f))
StaticSprite(bg1_sapling_v3, "scenic/background/vegetation", v4(115.0f, 25.0f, 20.0f, 40.0f), v2(0.0f, 0.0f))

StaticSprite(bg1_pine_tree_v1, "scenic/background/bg1_pine_tree", v4(0.0f, 0.0f, 90.0f, 170.0f), v2(0.0f, 0.0f))
StaticSprite(bg1_pine_tree_v2, "scenic/background/bg1_pine_tree", v4(90.0f, 0.0f, 90.0f, 170.0f), v2(0.0f, 0.0f))

StaticSprite(bg2_hills_v1, "scenic/background/bg2_hills", v4(0.0f, 0.0f, 200.0f, 40.0f), v2(0.0f, 21.0f))
StaticSprite(bg2_hills_v2, "scenic/background/bg2_hills", v4(0.0f, 40.0f, 200.0f, 40.0f), v2(0.0f, 21.0f))

StaticSprite(bg2_shrub_v1, "scenic/background/vegetation", v4(0.0f, 25.0f, 25.0f, 20.0f), v2(0.0f, 0.0f))
StaticSprite(bg2_shrub_v2, "scenic/background/vegetation", v4(25.0f, 25.0f, 25.0f, 20.0f), v2(0.0f, 0.0f))
StaticSprite(bg2_shrub_v3, "scenic/background/vegetation", v4(50.0f, 25.0f, 25.0f, 20.0f), v2(0.0f, 0.0f))

StaticSprite(bg2_pine_tree_v1, "scenic/background/bg2_pine_tree", v4(0.0f, 0.0f, 40.0f, 110.0f), v2(0.0f, 0.0f))
StaticSprite(bg2_pine_tree_v2, "scenic/background/bg2_pine_tree", v4(40.0f, 0.0f, 40.0f, 110.0f), v2(0.0f, 0.0f))

StaticSprite(bg3_hills_v1, "scenic/background/bg3_hills", v4(0.0f, 0.0f, 200.0f, 40.0f), v2(0.0f, 17.0f))

StaticSprite(bg3_shrub_v1, "scenic/background/vegetation", v4(0.0f, 45.0f, 15.0f, 10.0f), v2(0.0f, 0.0f))
StaticSprite(bg3_shrub_v2, "scenic/background/vegetation", v4(15.0f, 45.0f, 15.0f, 10.0f), v2(0.0f, 0.0f))
StaticSprite(bg3_shrub_v3, "scenic/background/vegetation", v4(30.0f, 45.0f, 15.0f, 10.0f), v2(0.0f, 0.0f))
StaticSprite(bg3_shrub_v4, "scenic/background/vegetation", v4(45.0f, 45.0f, 15.0f, 10.0f), v2(0.0f, 0.0f))

StaticSprite(bg3_pine_tree_v1, "scenic/background/bg3_pine_tree", v4(0.0f, 0.0f, 20.0f, 50.0f), v2(0.0f, 0.0f))
StaticSprite(bg3_pine_tree_v2, "scenic/background/bg3_pine_tree", v4(20.0f, 0.0f, 20.0f, 50.0f), v2(0.0f, 0.0f))
StaticSprite(bg3_pine_tree_v3, "scenic/background/bg3_pine_tree", v4(40.0f, 0.0f, 20.0f, 50.0f), v2(0.0f, 0.0f))
StaticSprite(bg3_pine_tree_v4, "scenic/background/bg3_pine_tree", v4(60.0f, 0.0f, 20.0f, 50.0f), v2(0.0f, 0.0f))
StaticSprite(bg3_pine_tree_v5, "scenic/background/bg3_pine_tree", v4(80.0f, 0.0f, 20.0f, 50.0f), v2(0.0f, 0.0f))
StaticSprite(bg3_pine_tree_v6, "scenic/background/bg3_pine_tree", v4(100.0f, 0.0f, 20.0f, 50.0f), v2(0.0f, 0.0f))
StaticSprite(bg3_pine_tree_v7, "scenic/background/bg3_pine_tree", v4(120.0f, 0.0f, 20.0f, 50.0f), v2(0.0f, 0.0f))
StaticSprite(bg3_pine_tree_v8, "scenic/background/bg3_pine_tree", v4(140.0f, 0.0f, 20.0f, 50.0f), v2(0.0f, 0.0f))

// Icons
StaticSprite(y_axis_arrow_icon, "icon/axis_icons", v4(0.0f, 0.0f, 7.0f, 40.0f), v2(0.0f, 0.0f))
StaticSprite(x_axis_arrow_icon, "icon/axis_icons", v4(0.0f, 33.0f, 40.0f, 7.0f), v2(0.0f, 0.0f))
StaticSprite(middle_axis_icon, "icon/axis_icons", v4(33.0f, 0.0f, 7.0f, 7.0f), v2(0.0f, 0.0f))