/* --- sprite_name, sprite_atlas_path, sprite_source, sprite_offset --- */
StaticSprite(ground_arctic, "scenic/biome_ground", v4(0.0f, 0.0f, 100.0f, 150.0f), v2(0.0f, 147.0f))
StaticSprite(ground_desert, "scenic/biome_ground", v4(100.0f, 0.0f, 100.0f, 150.0f), v2(0.0f, 147.0f))
StaticSprite(ground_plains, "scenic/biome_ground", v4(200.0f, 0.0f, 100.0f, 150.0f), v2(0.0f, 147.0f))
StaticSprite(ground_forest, "scenic/forest_ground", v4(0.0f, 0.0f, 100.0f, 90.0f), v2(0.0f, 87.0f))

StaticSprite(pine_tree_1, "scenic/trees/pine_tree_1", v4(0.0f, 0.0f, 150.0f, 260.0f), v2(0.0f, 0.0f))

StaticSprite(player, "entity/player/temp_player", v4(0.0f, 0.0f, 14.0f, 35.0f), v2(0.0f, 0.0f))

StaticSprite(flint_sword_icon, "item/flint_sword", v4(0.0f, 0.0f, 16.0f, 16.0f), v2(6.0f, 2.0f))
StaticSprite(flint_sword_ground, "item/flint_sword_ground", v4(0.0f, 0.0f, 24.0f, 24.0f), v2(0.0f, 0.0f))

StaticSprite(shia, "item/shia", v4(0, 0, 800, 1200), v2(0, 0))