#define TS_APP_FILENAME "arcane"
#define TS_APP_WINDOW_TITLE "Arcane"
#define TS_APP_DEFAULT_WINDOW_WIDTH 1280
#define TS_APP_DEFAULT_WINDOW_HEIGHT 720
#define TS_APP_PERMANENT_STORAGE_SIZE Megabytes(1024)
#define TS_APP_SCRATCH_STORAGE_SIZE Megabytes(64)
